volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: enigmatica/foodgram_backend
    volumes:
      - media:/app/media
      - static:/app/static
    env_file: .env

  frontend:
    # container_name: foodgram-front
    # build: ../frontend
    image: enigmatica/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: enigmatica/foodgram_nginx
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media


  # nginx:
  #   container_name: foodgram-proxy
  #   image: nginx:1.25.4-alpine
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf 
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - ../docs/:/usr/share/nginx/html/api/docs/
