volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: enigmatica/foodgram_backend
    ports:
      - "9123:9123"
    volumes:
      - media:/app/media
      - static:/app/static
    env_file: .env

  frontend:
    image: enigmatica/foodgram_frontend
    # command: npm run build && cp -r ????????? /app/result_build/
    volumes:
      - static:/app/result_build/
    env_file: .env

  # nginx:
  #   image: enigmatica/foodgram_nginx
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
  #     - frontend
  #   volumes:
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - ../docs/:/usr/share/nginx/html/api/docs/
  #     - static:/static
  #     - media:/media

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8888:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static
      - media:/var/html/media
