# Generated by Django 4.2.21 on 2025-06-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Короткая ссылка на рецепт'),
        ),
    ]
