# Generated by Django 4.2.21 on 2025-05-24 05:41

import django.core.validators
from django.db import migrations, models
import foodgram.validators


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+-]+\\Z'), foodgram.validators.validate_name]),
        ),
    ]
